"""Global Constants for Riftwalker: Paradox Protocol"""

# Window & Display
WINDOW_TITLE = b"Riftwalker: Paradox Protocol [CSE423 Final Project]"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 800
TARGET_FPS = 60


# Game State Constants
STATE_STORY = "STORY"
STATE_MENU = "MENU"
STATE_PLAYING = "PLAYING"
STATE_TELEPORTING = "TELEPORTING"
STATE_GAME_OVER = "GAME_OVER"
STATE_VICTORY = "VICTORY"


# Scene / Arena Identifiers
ARENA_01_KEPLER_RELAY = "ARENA_01_KEPLER_RELAY"
ARENA_02_SUNDERED_RIFT = "ARENA_02_SUNDERED_RIFT"

# Enemy Identifiers
ENEMY_MELEE_RIFT_STALKER = "ENEMY_MELEE_RIFT_STALKER"
ENEMY_RANGED_RIFT_SPITTER = "ENEMY_RANGED_RIFT_SPITTER"
BOSS_RIFT_GUARDIAN = "BOSS_RIFT_GUARDIAN"

# Player Attributes
MAX_PLAYER_HP = 100.0
PLAYER_MOVE_SPEED = 14.0
PLAYER_ROTATION_SPEED = 120.0  # degrees per second
PLAYER_RADIUS = 1.0
PLAYER_HEIGHT = 2.4

# Blink Teleport
BLINK_DISTANCE = 12.0
BLINK_COOLDOWN = 3.0  # seconds
BLINK_ENERGY_COST = 20.0

# Chrono Slow Mechanics
MAX_CHRONO_CHARGE = 100.0
CHRONO_SLOW_DURATION = 5.0    # 5 seconds active duration
CHRONO_SLOW_FACTOR = 0.30     # 30% speed for enemies/world
CHRONO_CHARGE_KILL_STALKER = 25.0
CHRONO_CHARGE_KILL_SPITTER = 35.0
CHRONO_CHARGE_BOSS_HIT = 10.0
CHRONO_CHARGE_PICKUP = 25.0

# Teleportation Sequence
TELEPORT_ACTIVATION_RADIUS = 3.5
TELEPORT_DURATION = 1.8  # seconds for vortex effect

# Weapons & Combat
PRIMARY_FIRE_COOLDOWN = 0.15  # seconds
PRIMARY_FIRE_DAMAGE = 25.0
PRIMARY_FIRE_RANGE = 120.0

# Camera Parameters
FOV_DEGREES = 60.0
NEAR_PLANE = 0.1
FAR_PLANE = 500.0
MOUSE_SENSITIVITY = 0.15

# Camera Pitch Limits & Offsets
FP_CAM_PITCH_MIN = -85.0
FP_CAM_PITCH_MAX = 85.0
TP_CAM_DISTANCE = 7.0
TP_CAM_HEIGHT = 1.8
TP_CAM_PITCH_MIN = -60.0
TP_CAM_PITCH_MAX = 65.0


# Colors (RGBA tuples 0.0 - 1.0)
COLOR_KEPLER_AMBIENT = (0.2, 0.25, 0.3, 1.0)
COLOR_SUNDERED_AMBIENT = (0.25, 0.15, 0.3, 1.0)
COLOR_CYAN_GLOW = (0.0, 0.85, 1.0, 1.0)
COLOR_MAGENTA_GLOW = (1.0, 0.1, 0.8, 1.0)
COLOR_HUD_HEALTH = (0.1, 0.9, 0.3, 0.9)
COLOR_HUD_CHRONO = (0.0, 0.7, 1.0, 0.9)
